CREATE TABLE CUSTOMER
(
    C_CUSTKEY    INT PRIMARY KEY,
    C_NAME       STRING(25),
    C_ADDRESS    STRING(40),
    C_NATIONKEY  INT,
    C_PHONE      STRING(15),
    C_ACCTBAL    DECIMAL,
    C_MKTSEGMENT STRING(10),
    C_COMMENT    STRING(117)
);
