CREATE TABLE SUPPLIER
(
    S_SUPPKEY   INT PRIMARY KEY,
    S_NAME      STRING(25),
    S_ADDRESS   STRING(40),
    S_NATIONKEY INT,
    S_PHONE     STRING(15),
    S_ACCTBAL   DECIMAL,
    S_COMMENT   STRING(101),
);
