connector.name=iceberg
iceberg.catalog.type=nessie
iceberg.nessie-catalog.uri=http://iceberg-catalog:19120/api/v2
iceberg.nessie-catalog.ref=main
iceberg.nessie-catalog.default-warehouse-dir=local:///warehouse
iceberg.add-files-procedure.enabled=true
iceberg.register-table-procedure.enabled=true
fs.local.enabled=true
local.location=/opt/dbprove
