connector.name=hive
hive.metastore=thrift
hive.metastore.uri=thrift://127.0.0.1:9083
hive.storage-format=ORC
hive.compression-codec=ZSTD
hive.non-managed-table-writes-enabled=true
fs.local.enabled=true
local.location=local:///mnt/nvme
