CREATE TABLE LINEITEM
(
    L_ORDERKEY      INT,
    L_PARTKEY       INT,
    L_SUPPKEY       INT,
    L_LINENUMBER    INT,
    L_QUANTITY      DECIMAL,
    L_EXTENDEDPRICE DECIMAL,
    L_DISCOUNT      DECIMAL,
    L_TAX           DECIMAL,
    L_RETURNFLAG    STRING(1),
    L_LINESTATUS    STRING(1),
    L_SHIPDATE      DATE,
    L_COMMITDATE    DATE,
    L_RECEIPTDATE   DATE,
    L_SHIPINSTRUCT  STRING(25),
    L_SHIPMODE      STRING(10),
    L_COMMENT       STRING(44)
);
