CREATE TABLE ORDERS
(
    O_ORDERKEY      INT PRIMARY KEY,
    O_CUSTKEY       INT,
    O_ORDERSTATUS   STRING(1),
    O_TOTALPRICE    DECIMAL,
    O_ORDERDATE     DATE,
    O_ORDERPRIORITY STRING(15),
    O_CLERK         STRING(15),
    O_SHIPPRIORITY  INT,
    O_COMMENT       STRING(79)
);
